# Generated by Django 3.2.5 on 2021-07-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='terminals',
            field=models.ManyToManyField(blank=True, to='core.Terminal'),
        ),
        migrations.AddField(
            model_name='sessionconfiguration',
            name='terminals',
            field=models.ManyToManyField(blank=True, to='core.Terminal'),
        ),
    ]
