# Generated by Django 3.2.5 on 2021-07-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210717_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='terminal',
            name='access_key',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
