# Generated by Django 3.2.5 on 2021-07-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_zone_active_session'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zone',
            name='operators',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='services',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='terminals',
        ),
        migrations.AddField(
            model_name='operator',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zone'),
        ),
        migrations.AddField(
            model_name='service',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zone'),
        ),
        migrations.AddField(
            model_name='terminal',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zone'),
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('LOGIN', 'Вход оператора в систему'), ('LOGOUT', 'Выход оператора из системы'), ('TICKET-ISSUE', 'Выдача билета'), ('TICKET-TAKE', 'Взятие билета оператором'), ('TICKET-CLOSE', 'Закрытие билета'), ('TICKET-SKIP', 'Пропуск билета'), ('SESSION-NEW', 'Создание новой сессии'), ('SESSION-PAUSE', 'Приостановка выдачи билетов'), ('SESSION-RESUME', 'Возобновление выдачи билетов'), ('SESSION-FINISH', 'Завершение сессии'), ('SESSION-CHANGE', 'Редактирование настроек сессии'), ('ZONE-NEW-ACTIVE-SESSION', 'Запуск новой активной сессии в зоне')], max_length=50)),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.operator')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.service')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.session')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.terminal')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.ticket')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.zone')),
            ],
        ),
    ]
