# Generated by Django 3.2.5 on 2021-07-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210717_1302'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='current_token',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
