# Generated by Django 3.2.5 on 2021-07-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210718_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='zone',
        ),
        migrations.AddField(
            model_name='zone',
            name='services',
            field=models.ManyToManyField(blank=True, to='core.Service'),
        ),
    ]
