# Generated by Django 3.2.5 on 2021-07-21 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210718_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesessionlimit',
            name='service_is_disabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Вход оператора в систему'), ('LOGOUT', 'Выход оператора из системы'), ('TICKET-ISSUE', 'Выдача билета'), ('TICKET-TAKE', 'Взятие билета оператором'), ('TICKET-CLOSE', 'Закрытие билета'), ('TICKET-SKIP', 'Пропуск билета'), ('SESSION-NEW', 'Создание новой сессии'), ('SESSION-PAUSE', 'Приостановка выдачи билетов'), ('SESSION-RESUME', 'Возобновление выдачи билетов'), ('SESSION-FINISH', 'Завершение сессии'), ('SESSION-CHANGE', 'Редактирование настроек сессии')], max_length=50),
        ),
    ]
