# Generated by Django 3.2.5 on 2021-07-17 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_operator_current_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='operator',
            name='current_token',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
