# Generated by Django 3.2.5 on 2021-07-17 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210717_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_taken',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
