# Generated by Django 3.2.5 on 2021-07-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_operator_current_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
