# Generated by Django 3.2.5 on 2021-07-17 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_operator_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session',
            name='operators',
        ),
        migrations.RemoveField(
            model_name='session',
            name='services',
        ),
        migrations.RemoveField(
            model_name='session',
            name='terminals',
        ),
    ]
