# Generated by Django 3.2.5 on 2021-07-18 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210717_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.operator'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.session'),
        ),
    ]
